name: Build

on:
  # Trigger the workflow on push to the master or feature branches and when a tag is created.
  pull_request:
  push:
    branches:
      - master
      - feature/**
    tags:
      - 'v*.*.*'

env:
  # Set environment variables for registry image and versions of Guix and BuildKit.
  REGISTRY_IMAGE: mryash/guix
  GUIX_VERSION: 1.4.0
  BUILDKIT_VERSION: 0.13.0

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Matrix of platforms with Docker and corresponding Guix architectures.
        platform: [
          { docker: linux/amd64, guix: x86_64-linux },
          { docker: linux/386, guix: i686-linux }
          # TODO: The following platforms have issues that need to be resolved.
          # { docker: linux/arm/v7, guix: armhf-linux }, # Issue: Invalid argument
          # { docker: linux/arm64/v8, guix: aarch64-linux }, # Issue: Cannot allocate memory
          # { docker: linux/ppc64le, guix: powerpc64le-linux } # Issue: Cannot allocate memory
        ]

    steps:
      - name: Prepare
        run: |
          # Extract Docker platform and format it for use in the environment.
          platform=${{ matrix.platform.docker }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Set metadata tags for Docker images.
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Enable QEMU for emulating different CPU architectures.

      - name: Docker Setup BuildX
        uses: docker/setup-buildx-action@v3
        with:
          # Set up BuildX with the specified version.
          version: v${{ env.BUILDKIT_VERSION }}

      - name: Verify Docker BuildX Version
        run: docker buildx version
        # Verify the installed version of Docker BuildX.

      - name: Create a new builder instance
        run: |
          # Create and use a new BuildX builder instance with insecure security entitlements.
          docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'

      - name: Authenticate to Docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          # Authenticate to DockerHub using secrets (skipped for pull requests).
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          # Build and push Docker images to specified platforms and set necessary labels.
          platforms: ${{ matrix.platform.docker }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          allow: security.insecure
          build-args: |
            METACALL_GUIX_VERSION=${{ env.GUIX_VERSION }}
            METACALL_GUIX_ARCH=${{ matrix.platform.guix }}

      - name: Export digest
        run: |
          # Save the image digest to a temporary directory.
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          # Upload the digests as artifacts for later use in manifest creation.
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge digests for the manifest
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - build

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          # Download all digests from the previous build job.
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Set up BuildX again for creating the manifest.
          version: v${{ env.BUILDKIT_VERSION }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Fetch metadata again for creating the manifest.
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Authenticate to Docker registry
        uses: docker/login-action@v3
        with:
          # Authenticate to DockerHub for pushing the manifest.
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          # Extract tags from metadata and push the manifest list using all digests.
          echo 'Meta output JSON: ${{ toJson(steps.meta.outputs.json) }}'
          TAGS=$(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[]')
          TAG_ARGS=$(echo "$TAGS" | sed 's/^/--tag /')
          docker buildx imagetools create \
          $TAG_ARGS \
          $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
