name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - feature/**
    tags:
      - 'v*.*.*'

env:
  REGISTRY_IMAGE: mryash/guix
  GUIX_VERSION: 1.4.0
  BUILDKIT_VERSION: 0.13.0

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [
          { docker: linux/amd64, guix: x86_64-linux },
          { docker: linux/386, guix: i686-linux },
          # TODO: 
          # { docker: linux/arm/v7, guix: armhf-linux }, # guix error: cloning builder process: Invalid argument
          # { docker: linux/arm64/v8, guix: aarch64-linux }, # ERROR: ResourceExhausted: cannot allocate memory
          # { docker: linux/ppc64le, guix: powerpc64le-linux } # ERROR: ResourceExhausted: cannot allocate memory
        ]

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform.docker }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker Setup BuildX
        uses: docker/setup-buildx-action@v3
        with:
          version: v${{ env.BUILDKIT_VERSION }}

      - name: Verify Docker BuildX Version
        run: docker buildx version

      - name: Create a new builder instance
        run: docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'

      - name: Authenticate to Docker registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform.docker }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          allow: security.insecure
          build-args: |
            METACALL_GUIX_VERSION=${{ env.GUIX_VERSION }}
            METACALL_GUIX_ARCH=${{ matrix.platform.guix }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge digests for the manifest
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - build

    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v${{ env.BUILDKIT_VERSION }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Authenticate to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          TAGS=$(echo '${{ steps.meta.outputs.json }}' | jq -r '.tags[]')
          TAG_ARGS=$(echo "$TAGS" | sed 's/^/--tag /')
          docker buildx imagetools create \
          --annotation "org.opencontainers.image.authors=dvdksn" \
          $TAG_ARGS \
          $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
